name: DocC GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'Sources/**/*.swift'
      - ".github/workflows/docc-github-pages.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2

      - name: Build DocC for EventProducer
        run: |
          swift package --allow-writing-to-directory ./docs/EventProducer \
            generate-documentation --target EventProducer \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path swift-event-sourcing-cqrs/EventProducer \
            --output-path ./docs/EventProducer
          
      - name: Build DocC for EventConsumer
        run: |
          swift package --allow-writing-to-directory ./docs/EventConsumer \
            generate-documentation --target EventConsumer \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path swift-event-sourcing-cqrs/EventConsumer \
            --output-path ./docs/EventConsumer

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - uses: actions/deploy-pages@v4
